services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3docs\BlogExample\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  T3docs\BlogExample\Property\TypeConverters\HiddenCommentConverter:
    tag:
      - name: extbase.type_converter
        priority: 2
        target: T3docs\BlogExample\Domain\Model\Comment
        sources: int,string
