name: tests

on:
  push:
  pull_request:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.2'
          - '8.3'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s lint

  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    env:
      php: '8.2'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install testing system
        run: Build/Scripts/runTests.sh -p ${{ env.php }} -s composerUpdate

      - name: Composer validate
        run: Build/Scripts/runTests.sh -p ${{ env.php }} -s composerValidate

      - name: Composer normalize
        run: Build/Scripts/runTests.sh -p ${{ env.php }} -s composerNormalize -n

      - name: CGL
        run: Build/Scripts/runTests.sh -n -p ${{ env.php }} -s cgl

      - name: phpstan
        run: Build/Scripts/runTests.sh -n -p ${{ env.php }} -s phpstan
