name: tests

on:
  push:
  pull_request:

jobs:
  CGL:
    name: Coding Style Check (TYPO3 Community CGL)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Composer
        run: Build/Scripts/runTests.sh -t 13 -p 8.2 -s composerUpdate

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -t 13 -p 8.2 -s lint

      - name: Validate code against CGL
        run: Build/Scripts/runTests.sh -t 13 -p 8.2 -s cgl -n

  testsuite:
    name: Code quality

    needs: CGL

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '8.2'
          - '8.3'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install testing system
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 13 -s composerUpdate

      - name: Unit tests
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 13 -s unit

      - name: Functional tests with mariadb
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 13 -d mariadb -s functional

      - name: Functional tests with postgres
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 13 -d postgres -s functional

      - name: Functional tests with sqlite
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 13 -d sqlite -s functional
